### ISSUE TITLE
Port over Useful Services from Graffl-Core

### ISSUE THREAD

**Issue by grafflr2** [grafflr/ask-owl#2]
There are value-add components for dealing with OWL relationships.

I have to decide if that's something I want to add here, or if this should be kept as a generic microservice.

**Comment by grafflr2** [comment]
For example, in NER Transformation:
```python
def process(d_results: dict) -> dict:
    d = defaultdict(list)

    for k in d_results:
        d_sub = d_results[k]
        for ner in d_results[k]:
            d[k.lower()].append(ner.upper().strip())

    return d
```

The casing is very important here.

**Comment by grafflr2** [comment]
This lookup transform could be useful
```yaml
  - classname: <Class>Lookup
    filename: <file>_lookup
    transformers:
      - lowercase
      - lookup
    queries:
      - lookup.sparql
    files:
      - <file>.txt
```

Simply as a way of extracting n-grams from the OWL model.
